### ISSUE TITLE
`/activity server` checklist

### ISSUE THREAD

**Issue by Rajdave69** [Some-Random-Guys/Analytics-Package#1]
This is a checklist for the `/activity server` command. (activity.py)

- [x] 1d - no custom timeperiod
- [x] 3d - no custom timeperiod
- [x] 5d - no custom timeperiod
- [x] 1w - no custom timeperiod
- [x] 2w - no custom timeperiod
- [x] 1m - no custom timeperiod
- [x] 3m - no custom timeperiod
- [x] 6m - no custom timeperiod
- [x] 9m - no custom timeperiod
- [x] 1y - no custom timeperiod
- [x] 2y - no custom timeperiod
- [x] 3y - no custom timeperiod
- [x] all time - no custom timeperiod

**Comment by Rajdave69** [comment]
3d - shows time instead of date in x axis
5d - not implemented in discord bot
3m - shows date instead of month
6m - shows date instead of month
9m - not implemented in discord bot
3y - shows month instead of year
all time - shows month instead of year

**Comment by Rajdave69** [comment]
3d, all time fully fixed; 
3m, 6m, 3y, partially fixed in ea39be14f210df3b89824cea3eb8795cbe547de9

5d, 9m tested
